#!/bin/bash
# WOLFPACK EDGEPACK CHOICE 1 - STARTUP CONFIRMATION
# This script confirms all anti-churn and edge-preserving features are active on startup

echo "======================================================================="
echo "  WOLFPACK EDGEPACK CHOICE 1 - STARTUP CONFIRMATION"
echo "======================================================================="
echo ""
echo "✅ All features are ACTIVE by default when you start the trading engine"
echo ""
echo "Anti-Churn Features (Built-In):"
echo "  • Spread Guard: Rejects spreads > 1.2 pips"
echo "  • 30s Min Hold: Prevents rapid-fire trades"
echo "  • Cost Logging: Records all trade costs"
echo ""
echo "Edge-Preserving Features (Built-In):"
echo "  • Regime Gate: Requires ML confidence >= 0.65"
echo "  • Hedge Recovery: Safe loss recovery (max 1 layer)"
echo "  • Surgeon Harmony: Delays trailing until +0.8R profit"
echo ""
echo "Charter Limits (Enforced):"
echo "  • Max Spread: 1.2 pips"
echo "  • Daily Loss Breaker: 3%"
echo "  • Max Margin: 25%"
echo "  • Max Positions: 12 total, 4 per symbol"
echo ""
echo "Configuration: config/features.json (all features ON)"
echo ""
echo "To verify features are active, run:"
echo "  ./tools/verify_wolfpack_edgepack.sh"
echo ""
echo "To start the trading engine:"
echo "  python3 oanda_trading_engine.py"
echo ""
echo "All anti-churn features will be active automatically!"
echo "======================================================================="
